core/src/tab/tab.stories.tsx
core/src/tab/tab.tsx

- change uncontrol tab to control tab
- add callback when changing tab

feat: support both controlled and uncontrolled for tab

---

core/src/date-input/date-input.css
core/src/date-input/date-input.stories.tsx
core/src/date-input/date-input.tsx
core/src/date-input/format.ts
core/src/input/input.tsx
core/src/text/text.module.css

Feat(core): add min, max, disabled props to DateInput

---

core/src/button/flat.module.css
core/src/input/input.tsx
core/tsconfig.json

Please see commits and their description

Refactor(core): Cleanup unused stuffs

---

core/.storybook/preview.css
core/.storybook/preview.js
core/.storybook/syntax.css
core/src/_gallery/toolbar/toolbar.module.css
core/src/_gallery/toolbar/toolbar.tsx

Docs(core): Improve source code preview appearance

---

core/src/_gallery/button/size.tsx
core/src/_gallery/gallery.tsx
core/src/_gallery/section/section.module.css
core/src/button/button.module.css
core/src/button/button.tsx

Add large button, which is trivial. Most changes is in the gallery to re-organize the size and icon example of Button

Feat(core): Add large button

---

core/package.json
core/src/_gallery/toolbar/toolbar.module.css
core/src/_gallery/toolbar/toolbar.tsx
site/components/hero/hero.module.css
site/components/hero/hero.tsx
site/package.json
site/pages/index.module.css
site/pages/index.tsx
site/yarn.lock

Feat(site): Add hero section

---

core/package.json
core/src/_gallery/selection/select.tsx
site/package.json
site/yarn.lock

Fix(site): Fix mismatch disabled option between Server and Client

---

core/src/checkbox/shared.module.css
core/src/global.css
core/src/table/table.module.css

fix: icon should be behind header of table

---

core/.storybook/syntax.css
core/src/_story.ts
core/src/date-input/date-input.stories.tsx
core/src/input/input.stories.tsx
core/src/select/select.stories.tsx
core/src/table/table.stories.tsx
core/src/text-area/text-area.stories.tsx
core/src/toast/toast.stories.tsx

Please see https://github.com/moaijs/moai/pull/75/files#diff-7576690baaf4d49a5584bd67fedfb38ec5651990b2398b8f393fe1781608373aR29-R40

Docs(core): Fix primary stories have incorrect code snippet

---

core/src/checkbox/shared.module.css
core/src/dialog/main/main.module.css
core/src/global.css
core/src/input/input.module.css
core/src/outline/outline.module.css
core/src/popover/pane/pane.module.css
core/src/select/select.module.css
core/src/tab/tab.module.css
core/src/table/table.module.css
core/src/toast/container/container.module.css

Follow up of https://github.com/moaijs/moai/pull/72#pullrequestreview-616981556
In this PR we centralize all z-indexes and, more importantly, add comments to explain our ordering

Refactor(core): Centralize z-indexes

---

core/src/_story.ts
core/src/input/input.stories.tsx

Fix arg type on [PR#79](https://github.com/moaijs/moai/pull/79#discussion_r599678787)

Docs(core): Refactor arg type of Input doc

---

core/src/select/select.tsx

Option's value is set incorrectly to the "id" attribute

Fix(core): Fix select option's values

---

core/src/select/select.tsx

Fix(core): Fix incorrect option value

---

core/src/table/cell/cell.tsx
core/src/table/row/row.tsx
core/src/table/table.tsx

Issue: https://github.com/moaijs/moai/issues/95

Feat(core): Allow rowKey to use index as key

---

core/src/table/cell/cell.tsx
core/src/table/row/row.tsx
core/src/table/table.tsx

Issue: https://github.com/moaijs/moai/issues/96
Block by: https://github.com/moaijs/moai/pull/101 (merge that PR before this PR)

Feat(core): Allow column.render to use row index

---

.gitignore
core/src/table/table.module.css
core/src/table/table.stories.tsx
core/src/table/table.tsx

Feat(core): Table row with compact height

---

core/src/_gallery/button/style.tsx
core/src/button/button.tsx
core/src/button/flat.module.css

Feat(core): Support flat + highlight button

---

core/src/_gallery/table/table.tsx
core/src/table/fixed.module.css
core/src/table/table.stories.tsx
core/src/table/table.tsx

Should fix https://github.com/moaijs/moai/issues/85

Feat(core): Support fixed first & last column in table

---

core/src/tag/tag.stories.tsx

Fix Document: Tag page could not loaded

---

core/src/popover/pane/pane.tsx

Fix(core) Popover shadow should not have drop shadow

---

core/src/popover/popover.stories.tsx
core/src/popover/popover.tsx

Docs(core): Popover component

---

core/src/pagination/pagination.stories.tsx
core/src/pagination/pagination.tsx
core/src/tooltip/tooltip.stories.tsx
core/src/tooltip/tooltip.tsx

Update pages:
- Pagination
- Tooltip Resolve #114

Docs(core): Updated Pagination's doc and improved Tooltip's doc

---

core/src/popover/popover.tsx

Fix(core): Fixed Popover target extra "div" wrapper

---

core/src/index.ts

Fix(core): Add missing Empty component export

---

package.json

Feat(root): Support running prettier and fix linting in script

---

core/src/switcher/fake-switcher-option.tsx
core/src/switcher/switcher.stories.tsx
core/src/switcher/switcher.tsx

Feat(core): Improve Switcher and add doc

---

core/src/button/button.tsx

Fix(core): Fix spinner color in highlighted flat buttons

---

core/.storybook/manager.js
core/src/button/flat.module.css
core/src/index.ts
core/src/input/input.tsx
core/src/outline/outline.module.css
core/src/outline/outline.ts
core/src/style/base.css
core/src/style/reset.css
core/src/style/style.ts
core/src/table/cell/expand/expand.module.css
core/src/table/cell/expand/expand.tsx
core/src/text-area/text-area.tsx

- Please see the comment at top of "style/reset.css"
- Fixes #134

Fix(core): Use Tailwind Reset CSS

---

core/.storybook/syntax.css
core/package.json
core/src/form/error.tsx
core/src/form/form.stories.tsx
core/src/form/form.tsx
core/src/index.ts
core/src/input/input.tsx
core/src/text-area/text-area.tsx
core/yarn.lock

Should fix #130
Check this page on PR's deployment:

Feat(core): Support Formik out of the box

---

core/src/checkbox/checkbox.module.css
core/src/checkbox/outset.module.css

Fix(core) Radio button shouldn't match indeterminate

---

core/src/radio/radio.stories.tsx
core/src/radio/radio.tsx

Docs(core) Radio component

---

core/src/_story.tsx
core/src/button/button.tsx
core/src/date-input/date-input.tsx
core/src/div/div.tsx
core/src/form/form.stories.tsx
core/src/icon/icon.tsx
core/src/input/input.stories.tsx
core/src/input/input.tsx
core/src/switcher/switcher.tsx
core/src/tooltip/tooltip.stories.tsx

Problem: Missing ref when using NextLink (https://nextjs.org/docs/api-reference/next/link)

Fix(core) Missing ref when using with NextLink

---

core/src/toast/pane/pane.module.css
core/src/toast/pane/pane.tsx

#171  Add toastpane interface with optional styling for each toast type. Not sure if this is a good idea but there was an attempt :D

Add ToastPane interface

---

core/package.json
core/yarn.lock
docs/.storybook/main.js
docs/package.json
docs/yarn.lock
gallery/package.json
gallery/yarn.lock
site/next.config.js

Should also fix #183 because it happens due to missing "typescript" dependency in "docs"

Fix(all): Update dependencies 

---

core/src/dialog/dialog.tsx
core/src/dialog/native/confirm.tsx
core/src/dialog/native/prompt.tsx
core/src/dialog/sub/sub.module.css
docs/src/button.stories.tsx
docs/src/dialog.stories.tsx
gallery/src/button-1.tsx
gallery/src/button-2.tsx
gallery/src/dialog.tsx
gallery/src/index.tsx

Fix(docs): Improve Dialog doc

---

core/src/date-input/date-input.tsx
docs/.storybook/syntax.css
docs/src/date-input.stories.tsx
docs/src/utils/component.tsx

Please see the DateInput page in the deployment to review. This PR also includes some minor enhancements for the Doc in general, which are extracted to their own commits

Fix(docs): Improve doc for DateInput

---

CODE_OF_CONDUCT.md

Adopt Contributor Covenant Code of Conduct

---

lib/docs/src/components/table.stories.tsx

Fix(docs): Improve “selectable” and "rowClassName" sections in Table

---

.github/CONTRIBUTING.md
.github/DEVELOP.md
README.md

This PR adds:
- [CONTRIBUTING.md](https://github.com/moaijs/moai/blob/9e748ec6467e2c2419f29c126a0b1e1a68adf730/.github/CONTRIBUTING.md)
- [DEVELOP.md](https://github.com/moaijs/moai/blob/9e748ec6467e2c2419f29c126a0b1e1a68adf730/.github/DEVELOP.md)
and update:
- [README.md](https://github.com/moaijs/moai/blob/9e748ec6467e2c2419f29c126a0b1e1a68adf730/README.md)
(click on the file name to preview them in HTML)
Fixes #144 Fixes #232

Docs: Add CONTRIBUTING and update README

---

lib/core/src/text-area/text-area.module.css

TextArea display should be block, not the default inline-block

Fix(core): Fix TextArea display

---

lib/core/src/input/input.tsx
lib/core/src/utils/omit.ts
lib/docs/src/components/input.stories.tsx

Fix #160 Fix #159 , big thank to @monodyle

Feat(core): InputProps should inherit from built-in ones 

---

lib/core/src/input/input.tsx
lib/core/src/text-area/text-area.tsx
lib/docs/src/patterns/form.stories.tsx

Fix #231
The second commit is the one that fixes 231. The first commit is a change to the docs to use TextArea in the form example

Fix(core): TextArea should work with Form builders

---

lib/core/src/input/input.tsx

Fix(core): Fix custom props of Input

---

lib/core/src/input/input.tsx

Chore(core): Improve props extending in Input

---

lib/core/src/text-area/text-area.tsx
lib/docs/src/components/text-area.stories.tsx

Feat(core): Fix TextArea to extend from built-in props

---

.github/CONTRIBUTING.md

Solve #253 
@thien-do  Please install the bot before merging this PR.

Chore(all): Using all-contributors bot

---

core/src/dialog/native/prompt.tsx

Fix(dialog): fix typo

---

core/package.json
core/src/tree/row/row.tsx
core/src/tree/tree.tsx
core/src/tree/utils/add.ts
core/src/tree/utils/exist.ts
core/src/tree/utils/refresh.ts
core/src/tree/utils/remove.ts
core/src/tree/utils/update.ts
core/src/tree/utils/utils.ts
docs/src/components/tree.stories.tsx

- Expose TreeUtils (utilities to modify a Tree node, since Tree is a controlled component)
- Mark "level" as internal prop
- Use ActionMenu in Tree example

Fix(core): Expose TreeUtils

---

core/src/menu/item/item.tsx
docs/src/components/menu.stories.tsx

Fix: Fix missing interactive state in menu

---

core/src/icons/blank-icon.tsx
core/src/icons/icons.tsx

Add blank icon to resolve #281

Feat(core): Add Blank Icon

---

core/src/tag/tag.module.css
core/src/tag/tag.tsx
docs/src/components/tag.stories.tsx

**CHANGES**
- Fix #288 
- Fix #290

Chore(tag): Support forwardedRef and size

---

core/src/popover/popover.tsx

Chore(popover): Expose TargetProps, ContentProps

---

core/src/category/category.tsx

Hi @thien-do, i've just expose category names as an array to Resolve #284. Can you check whether this meet your expectation?

Feat(core): Add Category Color Names

---

core/src/button/button.tsx
test/src/button.test.tsx

All global attributes should be supported, but now I just only need "id" attribute 😄

Support "id" attribute in Button

---

src/docs/components/button-group.stories.tsx
src/docs/components/menu.stories.tsx
src/docs/components/step.stories.tsx
src/docs/components/text-area.stories.tsx
src/docs/components/tree.stories.tsx

Restore docs for the following components: Button Group, Menu, Step, Text Area, Tree
https://github.com/thien-do/moai/issues/304

RESTORE: Draft docs: Button Group, Menu, Step, Text Area, Tree

---

.storybook/docs/docs.css
.storybook/docs/page.tsx
package.json
pnpm-lock.yaml
src/docs/patterns/form.stories.tsx
src/docs/utils/parameter.ts

RESTORE: Patterns/Form

---

.storybook/docs/docs.css
src/gallery/gallery.tsx

https://github.com/thien-do/moai/issues/318

FIX: Incorrect font for <span> elements
